version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 18080:8080
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
  db:
    image: postgres
    restart: always
    hostname: dblojavirtual
    ports:
      - "5432:5432"
    networks:
      - lojavirtual
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=lojavirtual
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-volume:/etc/prometheus/
      - ./monitoria/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoria/alerts_rules.yml:/etc/prometheus/alerts_rules.yml
    ports:
      - "9090:9090"
    networks:
      - lojavirtual
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    networks:
      - lojavirtual
    volumes:
      - ./monitoria/alertmanager.yml:/etc/alertmanager.yml
      - alertmanager-data:/etc/alertmanager/data
    command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - lojavirtual
    depends_on:
      - prometheus

volumes:
  grafana-volume:
  prometheus-volume:
  alertmanager-data:

networks:
  lojavirtual:
    driver: bridge